# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/api/v1/images/5ada1b96-f7bb-4766-a4f6-e12fa166a723/data
Accept: application/json

###
